spring:
  application:
    name: seuCondominio
  datasource:
    url: jdbc:postgresql://localhost:5432/seuCondominio
    password: postgres
    username: postgres
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    password: ${EMAIL_PASSWORD}
    username: juancassemiro1@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  security:
    token:
      secret: 12345
